// Generated by scripts/generate-native-cid-unicode.mjs. Do not edit.
export const NATIVE_CID_TO_UNICODE_SOURCE_COMMIT = "2dd5e53fb74a01718b9dfd448a0d1cce6fff2aa5";
export const NATIVE_CID_TO_UNICODE_SOURCE_TREE_SHA256 = "464f4a9f43cc340dc0d03df28ccab42202a7e12f302813d4519e1572607c6be7";
export const NATIVE_CID_TO_UNICODE_COLLECTIONS = Object.freeze(["CNS1","GB1","Japan1","KR","Korea1"] as const);
export type NativeCidToUnicodeCollection = (typeof NATIVE_CID_TO_UNICODE_COLLECTIONS)[number];
export const NATIVE_CID_TO_UNICODE_METADATA = Object.freeze({"CNS1":Object.freeze({"registry":"Adobe","ordering":"CNS1","supplement":7,"maxCid":19178,"mappingCount":19179,"shardByteLength":76797}),"GB1":Object.freeze({"registry":"Adobe","ordering":"GB1","supplement":5,"maxCid":30283,"mappingCount":30284,"shardByteLength":121181}),"Japan1":Object.freeze({"registry":"Adobe","ordering":"Japan1","supplement":7,"maxCid":23059,"mappingCount":23060,"shardByteLength":104127}),"KR":Object.freeze({"registry":"Adobe","ordering":"KR","supplement":9,"maxCid":22896,"mappingCount":22897,"shardByteLength":92824}),"Korea1":Object.freeze({"registry":"Adobe","ordering":"Korea1","supplement":2,"maxCid":18351,"mappingCount":18076,"shardByteLength":75395})} as const);
const NATIVE_CID_TO_UNICODE_COLLECTION_SET: ReadonlySet<string> = new Set(NATIVE_CID_TO_UNICODE_COLLECTIONS);
export function isNativeCidToUnicodeCollection(value: string): value is NativeCidToUnicodeCollection {
  return NATIVE_CID_TO_UNICODE_COLLECTION_SET.has(value);
}
export async function importNativeCidToUnicodeShard(collection: NativeCidToUnicodeCollection): Promise<string> {
  switch (collection) {
    case "CNS1": return (await import("./CNS1")).default;
    case "GB1": return (await import("./GB1")).default;
    case "Japan1": return (await import("./Japan1")).default;
    case "KR": return (await import("./KR")).default;
    case "Korea1": return (await import("./Korea1")).default;
  }
}
