import {
  VERTEX_SHADER_SOURCE,
  FRAGMENT_SHADER_SOURCE,
  FILL_VERTEX_SHADER_SOURCE,
  FILL_FRAGMENT_SHADER_SOURCE,
  TEXT_VERTEX_SHADER_SOURCE,
  TEXT_FRAGMENT_SHADER_SOURCE,
  BLIT_VERTEX_SHADER_SOURCE,
  VECTOR_COMPOSITE_FRAGMENT_SHADER_SOURCE,
  RASTER_VERTEX_SHADER_SOURCE,
  RASTER_FRAGMENT_SHADER_SOURCE
} from "./nativeWebGlCoreShaders";
import { pdfShapeCoverageGlsl } from "./pdfShapeCoverage";

// Shared shader sources exposed for adapter integrations (Three/Babylon/native wrappers).
export const CORE_STROKE_VERTEX_SHADER_SOURCE = pdfShapeCoverageGlsl(VERTEX_SHADER_SOURCE);
export const CORE_STROKE_FRAGMENT_SHADER_SOURCE = pdfShapeCoverageGlsl(FRAGMENT_SHADER_SOURCE);
export const CORE_FILL_VERTEX_SHADER_SOURCE = pdfShapeCoverageGlsl(FILL_VERTEX_SHADER_SOURCE);
export const CORE_FILL_FRAGMENT_SHADER_SOURCE = pdfShapeCoverageGlsl(FILL_FRAGMENT_SHADER_SOURCE);
export const CORE_TEXT_VERTEX_SHADER_SOURCE = pdfShapeCoverageGlsl(TEXT_VERTEX_SHADER_SOURCE);
export const CORE_TEXT_FRAGMENT_SHADER_SOURCE = pdfShapeCoverageGlsl(TEXT_FRAGMENT_SHADER_SOURCE);
export const CORE_BLIT_VERTEX_SHADER_SOURCE = BLIT_VERTEX_SHADER_SOURCE;
export const CORE_VECTOR_COMPOSITE_FRAGMENT_SHADER_SOURCE = VECTOR_COMPOSITE_FRAGMENT_SHADER_SOURCE;
export const CORE_RASTER_VERTEX_SHADER_SOURCE = pdfShapeCoverageGlsl(RASTER_VERTEX_SHADER_SOURCE);
export const CORE_RASTER_FRAGMENT_SHADER_SOURCE = pdfShapeCoverageGlsl(RASTER_FRAGMENT_SHADER_SOURCE);

